// Copies web assets from project root into www/ for Capacitor.
// Single source of truth: edit files at the root, run `npm run mobile:sync`
// (or it runs automatically before `cap sync`).
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'www');

// Files/folders to ship to mobile (web assets only — no Node, no Electron).
// NOTE: supabase.js (Node module) is NOT shipped — mobile uses the
// supabase-js bundle loaded by auth-mobile.js instead.
const ASSETS = [
  'index.html',
  'styles',
  'src',
  'moodboard',
];

// Extra files we add specifically for the mobile build.
// Order matters: auth-mobile must load before mobile-shim so the shim
// can wire window.__gesturoAuth into electronAPI.
const MOBILE_ONLY = [
  'auth-mobile.js',
  'mobile-shim.js',
];

// Generate www/supabase-config.js so the mobile build has the public
// Supabase URL + publishable key inlined (no Node at runtime).
// Resolution order: .env file → process.env → config.js (fallback).
function generateSupabaseConfig() {
  let url = '', key = '';

  // 1) Try .env file
  const envPath = path.join(ROOT, '.env');
  if (fs.existsSync(envPath)) {
    const env = {};
    for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (!m) continue;
      let v = m[2];
      if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
        v = v.slice(1, -1);
      }
      env[m[1]] = v;
    }
    url = env.SUPABASE_URL || '';
    key = env.SUPABASE_PUBLISHABLE_KEY || env.SUPABASE_ANON_KEY || '';
  }

  // 2) Override with process.env if set (CI friendly)
  if (process.env.SUPABASE_URL) url = process.env.SUPABASE_URL;
  if (process.env.SUPABASE_PUBLISHABLE_KEY) key = process.env.SUPABASE_PUBLISHABLE_KEY;

  // 3) Fallback: read config.js (public values, safe to use)
  if (!url || !key) {
    try {
      const config = require(path.join(ROOT, 'config.js'));
      if (!url) url = config.SUPABASE_URL || '';
      if (!key) key = config.SUPABASE_PUBLISHABLE_KEY || '';
    } catch (_) {}
  }

  if (!url || !key) {
    console.error('ERROR: SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY could not be resolved from .env, env vars, or config.js');
    process.exit(1);
  }
  const out = `// Auto-generated by scripts/sync-web.js — do not edit.\nwindow.__SUPABASE_CONFIG = ${JSON.stringify({ url, key })};\n`;
  fs.writeFileSync(path.join(OUT, 'supabase-config.js'), out);
}

function rmrf(p) {
  if (fs.existsSync(p)) fs.rmSync(p, { recursive: true, force: true });
}

function copyRecursive(src, dest) {
  const stat = fs.statSync(src);
  if (stat.isDirectory()) {
    fs.mkdirSync(dest, { recursive: true });
    for (const entry of fs.readdirSync(src)) {
      copyRecursive(path.join(src, entry), path.join(dest, entry));
    }
  } else {
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
  }
}

rmrf(OUT);
fs.mkdirSync(OUT, { recursive: true });

for (const name of ASSETS) {
  const src = path.join(ROOT, name);
  if (!fs.existsSync(src)) {
    console.warn(`[sync-web] skipped (missing): ${name}`);
    continue;
  }
  copyRecursive(src, path.join(OUT, name));
}

for (const name of MOBILE_ONLY) {
  const src = path.join(ROOT, 'mobile', name);
  if (!fs.existsSync(src)) {
    console.warn(`[sync-web] skipped mobile-only (missing): ${name}`);
    continue;
  }
  copyRecursive(src, path.join(OUT, name));
}

generateSupabaseConfig();

// Inject the mobile bootstrap scripts into index.html (before </head>).
// Order: supabase-config → auth-mobile → mobile-shim → __gesturoAuth.init.
const indexPath = path.join(OUT, 'index.html');
if (fs.existsSync(indexPath)) {
  let html = fs.readFileSync(indexPath, 'utf8');
  const tags = [
    '<script src="supabase-config.js"></script>',
    '<script src="auth-mobile.js"></script>',
    '<script src="mobile-shim.js"></script>',
    '<script>document.addEventListener("DOMContentLoaded",()=>{window.__gesturoAuth&&window.__gesturoAuth.init()});</script>',
  ];
  const block = tags.filter((t) => !html.includes(t)).join('\n  ');
  if (block) {
    html = html.replace(/<\/head>/i, `  ${block}\n</head>`);
    fs.writeFileSync(indexPath, html);
  }
}

console.log('[sync-web] done →', OUT);
